store생성하기
kakao-tech-campus-2nd-step3/Team10_BE pull request #104
Opened 2024-11-07 19:27 UTC by canyos

## 해결하려는 문제가 무엇인가요?

- close #89

## 어떻게 해결했나요?

- store 생성하고 crud했습니다

## 코드 리뷰시 요청 사항

- 연관관계 일단 필요하다고 생각한 것만 했는데 어떤지 의견 궁금합니다

## 더 하고 싶은 말

-

2024-11-08 08:12 UTC, stopmin commented on src/main/java/poomasi/domain/auth/signup/service/SignupService.java
> +        Member newMember = new Member(null, email,
혹시 빌더 방식으로 만들어주시는건 어떨까요? null이 정확히 id인지 아닌지 가독성이 살짝 떨어진다는 생각이 드네요!

2024-11-08 08:25 UTC, stopmin requested changes
수고하셨습니다! 😊
### Store 위치 조정 제안
Store는 Product의 하위 개념으로 보기 어렵기 때문에, product 패키지에서 분리하여 독립적으로 관리하는 것이 좋을 것 같습니다.
### Store Validation 위치
Store에 대한 검증 로직은 Product가 아닌 Store 자체에서 처리하는 것이 더 적절해 보입니다. 현재 Product에서 store 설정 시 존재 여부를 검증하고 있는데, 이 로직을 Store에 위치시키면 더 명확하고 유지보수가 용이할 것입니다. 
### StoreService 리턴 타입 변경
StoreService에서 반환 타입을 StoreResponse가 아닌 Store로 변경하면 코드가 간결해질 것 같습니다. 또한, Store 내부에 findById 같은 메서드를 추가하여, StoreService 단에서 예외를 처리할 수 있도록 하면 좋겠습니다. 이렇게 하면 Product에서 유효하지 않은 Store를 설정하려 할 때 StoreService에서 자동으로 예외가 발생하여, 검증 책임이 분리되고 코드 유지보수에 유리해질 것입니다.

이런 구조를 통해 각 도메인이 자신의 검증을 담당할 수 있어 유지보수성이 높아질 것 같아요.

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/auth/signup/service/SignupService.java
> +        Member newMember = new Member(null, email,
혹시 빌더 방식으로 만들어주시는건 어떨까요? null이 정확히 id인지 아닌지 가독성이 살짝 떨어진다는 생각이 드네요!

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/member/entity/Member.java
> +    public Member(Long id, String email, String password, LoginType loginType, Role role) {
id는 빼셔도 될 것 같네요!

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/controller/StoreController.java
> +public class StoreController {
Store을 product안에 둘 필요는 없을 것 같아요. _store -> store로 밖으로 빼시는건 어떨까요?

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/controller/StoreController.java
> +    @PostMapping("/api/store")
반복되는 부분은 `@RequestMapping`으로 묶어주세용 ㅎ

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/dto/StoreFeeRequest.java
> +public record StoreFeeRequest(
혹시 이 DTO는 기능이 뭔가요?? fee만 있는 이유가 궁금합니다.

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/controller/StoreController.java
> +    public ResponseEntity<?> updateFee(@RequestBody StoreFeeRequest storeFeeRequest) {
store에 update Fee를 추가하신 동기가 궁금합니다 :D

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/dto/StoreRegisterRequest.java
> +        String businessNumber,
`@NotNull`과 같은 Validation을 추가해보는건 어떨까요?

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/dto/StoreResponse.java
> +        return new StoreResponse(
혹시 빌더로 생성해주시는건 어떨까요?인자가 많아지니 조금 가독성이 떨어질 수 있다고 생각해요 :)

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/entity/Store.java
> +    Long id;
접근제어자가 다 빠져있는 것 같아요 !! 확인 부탁드립니당.

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/repository/StoreRepository.java
> +    @Query("select  s from Store s where s.owner.id = :id")
findByOwnerId로 하시면 굳이 JPQL을 안짜고도 JPA에서 자동 생성될 것 같은데 어떻게 생각하시나욤!

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/service/StoreService.java
> +public class StoreService {
위에`Transaction(readonly=true)` 추가 하셔야 원하는 대로 동작할 것 같습니다 :)

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/service/StoreService.java
> +        if (store == null) {
혹시 널로 리턴해도 괜찮나요???

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/service/StoreService.java
> +                .orElseThrow(() -> new BusinessException(BusinessError.STORE_NOT_FOUND));
이 부분은 계속 반복되는 코드인 것 같은데 따로 빼는 것을 추천드립니다!

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +        Store store = storeRepository.findByMemberId(member.getId()).orElseThrow(()-> new BusinessException(BusinessError.STORE_NOT_FOUND));
이건 Product에서 할 예외처리는 아닌 것 같습니다. Store을 가져올 때부터 storeService단에서 Validation하는 것이 좋아보여요!

2024-11-08 08:25 UTC, stopmin commented on src/main/java/poomasi/domain/review/dto/ReviewResponse.java
> +                review.getReviewer().getMemberProfile()==null?"":review.getReviewer().getMemberProfile().getName(),
삼항연산자를 많이 쓰시는 것 같아요! 그런데 이곳에 사용하신 이유가 궁금해요. Review에서 profile이 없으면 안되지 않을까요?

2024-11-08 08:25 UTC, stopmin commented on src/test/java/poomasi/domain/store/StoreServiceTest.java
> +class StoreServiceTest {
오 !! 테스트 코드도 짜주셨네요!!

2024-11-08 11:21 UTC, canyos commented on src/main/java/poomasi/domain/auth/signup/service/SignupService.java
> +        Member newMember = new Member(null, email,
수정해볼게여

2024-11-08 11:22 UTC, canyos commented on src/main/java/poomasi/domain/product/_store/controller/StoreController.java
> +public class StoreController {
넵

2024-11-08 11:22 UTC, canyos commented on src/main/java/poomasi/domain/product/_store/dto/StoreFeeRequest.java
> +public record StoreFeeRequest(
update에서 가능하니까 아예뺄까요?

2024-11-08 11:22 UTC, canyos commented on src/main/java/poomasi/domain/product/_store/dto/StoreRegisterRequest.java
> +        String businessNumber,
넵

2024-11-08 11:23 UTC, canyos commented on src/main/java/poomasi/domain/product/_store/service/StoreService.java
> +        if (store == null) {
없으면 만드는 사이트 나와야되는데 404를 뱉는게 맞을까요? null보단?

2024-11-08 11:23 UTC, canyos commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +        Store store = storeRepository.findByMemberId(member.getId()).orElseThrow(()-> new BusinessException(BusinessError.STORE_NOT_FOUND));
수정해볼게여

2024-11-08 11:24 UTC, canyos commented on src/main/java/poomasi/domain/review/dto/ReviewResponse.java
> +                review.getReviewer().getMemberProfile()==null?"":review.getReviewer().getMemberProfile().getName(),
테스트하면서 memberProfile이없어서 그런데 나중에는 없앨 예정입니다. 
주석으로 적어둘게요

2024-11-08 11:59 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/dto/StoreFeeRequest.java
> +public record StoreFeeRequest(
혹시 store에 따로 금액이 있나용?!?!?!

2024-11-08 12:00 UTC, stopmin commented on src/main/java/poomasi/domain/product/_store/service/StoreService.java
> +        if (store == null) {
에러를 뱉는게 나을수도 있을 것 같아용 ㅎㅎ

2024-11-08 12:00 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +        Store store = storeRepository.findByMemberId(member.getId()).orElseThrow(()-> new BusinessException(BusinessError.STORE_NOT_FOUND));
굿굿

2024-11-08 12:00 UTC, stopmin commented on src/main/java/poomasi/domain/review/dto/ReviewResponse.java
> +                review.getReviewer().getMemberProfile()==null?"":review.getReviewer().getMemberProfile().getName(),
넵!

2024-11-09 00:57 UTC, canyos commented
지민님 피드백 수정했는데 한번 더 봐주시면 감사...

2024-11-09 15:01 UTC, merged