Feature/issue 17
kakao-tech-campus-2nd-step3/Team10_BE pull request #18
Opened 2024-09-26 04:07 UTC by canyos

## 해결하려는 문제가 무엇인가요?

- close #17

## 어떻게 해결했나요?

- 지민님 드래프트 기반으로 최대한 따라 짜봤습니다.
- 좀 지저분한 느낌이 없지않네요
- 상품은 farmer가 등록 후 pending상태에서 관리자 승인이 있어야 open으로 변경됩니다.
- 카테고리의 경우 관리자만 일단 등록 가능하게 했습니다.

## 더 하고 싶은 말

- 상품 조회는 column이 확정되면 추가로 넣겠습니다. 애매하네요.
- 유저 인가 끝나면 권한 확인 하는 것도 같이 하겠습니다.

2024-09-26 06:20 UTC, stopmin requested changes
전체적으로 약속한 규칙이랑 거의 다 맞춰져있는 것 같습니다!! 👍
리뷰 확인하시고 혹시나 이해가 잘 안되는 부분 있으면 연락 부탁드립니당 :D

굿굿~~!!

--- 
### 🤨 카테고리에 관해서
추가적으로 카테고리는 당분간 `ENUM`으로 두는 편이 나을 것이라고 판단됩니다.

왜냐하면, 상품에 있어서 카테고리는 저희가 약속한 바에 따르면, "열매 채소", "뿌리 채소"와 같이 채소/과일의 종류가 됩니다. 이런 경우에는 수정이든 업데이트가 자주 일어나지 않을 부분이라고 판단이 됩니다. 

따라서 enum으로 관리해도 충분하다고 판단됩니다. 이 카테고리에 대해서는 금요일 회의에 한번 정해보고, 일단 Category는 객체(entity)가 아닌 enum으로 수정하셔도 괜찮을 것 같네요!

### 수정이 필요한 부분
- product에 태그를 추가해주셔야 할 것 같습니다. 유기농/무농약과 같은 태그가 필요합니다. nullable하게 두시면 될 것 같습니다.

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/category/controller/CategoryController.java
> +public class CategoryController {
카테고리는 지금 당장은 DB로 CRUD가 필요할지 잘 모르겠습니다. ENUM으로 당장 관리해도 괜찮을 것 같다는 생각도 드는데 다른 분들 의견이 궁금합니다!!

@amm0124 @jjt4515

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/category/dto/CategoryRequest.java
> +public record CategoryRequest (String name){
오 약속한대로 구현하셨네요~~ 좋습니다 👍

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/category/dto/CategoryRequest.java
> +        return new Category(name);
지금당장은 필요없겠지만, 인자가 늘어날수록 가독성이 떨어질 수 있어요. (카테고리라 지금 당장은 급한 것 같진 않습니다)

나중에 Lombok의 `@Builder`를 참고해보시는 것도 좋을 것 같습니다!

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/controller/ProductFarmerController.java
> +@AllArgsConstructor
마찬가지로 공통되는 부분은 `@RequestMapping("/api/products")`로 묶으시면 될거같습니다.

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/dto/ProductListResponse.java
> +public class ProductListResponse {
여기가 비어있네요! 구현 예정인가욤?!

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/dto/ProductRegisterRequest.java
> +        Long userId, //등록한 사람
farmerId로 수정하셔도 좋을 것 같습니다.

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/entity/Product.java
> +    @Builder
좋네요~~

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/entity/Product.java
> +    public Product modify(ProductRegisterRequest productRegisterRequest) {
request로 넘기는거 좋습니다~~

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/entity/Product.java
> +    private ProductStatus status = ProductStatus.PENDING;
상품은 등록하자마자 open으로 두어도 괜찮을 것 같습니다.
그런데 quentity가 있어서 따로 open, close 두지 않아도 될 것 같은데 다른 분들은 어떻게 생각하시는지 궁금합니다!!

@jjt4515 @amm0124

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/entity/ProductStatus.java
> +public enum ProductStatus {
product에 status를 두는 것에 대해서는 다른 분들과 상의가 필요할 것 같습니다!!

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductAdminService.java
> +    public void openProduct(Long productId) {
상품을 판매 개시하는 용도인 것 같은데 validation도 일부 추가되어야 할 것 같네요.
그런데 open/close에 대해서는 논의가 필요할 것 같습니다.

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +    public Long registerProduct(String token, ProductRegisterRequest product) {
토큰을 서비스에서 직접적으로 다룰 필요가 없을 것 같은데 어떻게 생각하시는지 궁금합니다:D (아마 제가 제 코드에 판매자 인가?가 있어서 헷갈리셨을 수도 있을 것 같습니다!! 하핫,, 저는 농장에 대해서 자기 농장인가?를 의도로 했는데 제가 잘못 주석을 달아둔 것 보시고 이해하신 것 같습니다 ㅠㅠ)

서비스는 비지니스 계층을 관리해야하므로, 어느정도 책임을 분리할 필요가 있다고 생각합니다.

이후에 건호님, 진택님께서 `@PreAuthorize`, `@Secured`를 통해 인증하고, `SecurityContextHolder`를 통해서 간단하게 사용자 정보를 가져올 수 있게 된다면 자연스럽게 필요하지 않아질 로직이라고 생각합니다. 

토큰은 넘기지 않으셔도 될거같습니다. 넘긴다면 farmerId정도 넘기시면 될 것 같아요!

이 부분은 진택님, 건호님께서 보시면 좋을 것 같습니다.  @amm0124 @jjt4515

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +                .orElseThrow(() -> new BusinessException(BusinessError.PRODUCT_NOT_FOUND));
이 부분은 계속 반복될 수 있는 코드 같네요.

service 내에서 `getProduct()`를 두시고, 없을 경우 예외처리를 시키시고 해당 메소드를 활용해 (`this.getProduct()`로) 매번 반복되는 코드를 줄일 필요가 있을 것 같습니다 :D

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +                .orElseThrow(() -> new BusinessException(BusinessError.PRODUCT_NOT_FOUND));
마찬가지로 반복되는 코드라 service단에서 getProduct를 두시는 것을 추천드립니다.

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +        Product product = productRepository.findById(productId)
마찬가지로 반복되는 코드라 service단에서 getProduct를 두시는 것을 추천드립니다.

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/global/error/BusinessError.java
> +
앞에 각각 주석 // product, // category 부탁드립니다!

2024-09-26 06:20 UTC, stopmin commented on src/main/java/poomasi/domain/category/service/CategoryAdminService.java
> +        category = categoryRepository.save(category);
save에서 이미 id를 리턴하고 있는 것 것 같네요~~ 아래와 같이 줄이셔도 괜찮을 것 같습니다.

```java
return categoryRepository.save(request.toEntity())
```

2024-09-26 12:51 UTC, canyos commented
한번 바꿨는데 미정인건 정하고 한번에 수정하겠습니다.

2024-09-27 03:55 UTC, stopmin commented on src/main/java/poomasi/global/error/ExceptionAdvice.java
> +import lombok.extern.slf4j.Slf4j;
헉 말씀드리는걸 까먹은 것 같습니다!! 저희 formatter는 googleStyle로 설정하시고 indent는 따로 4칸으로 수정해주셔야합ㄴ디ㅏ!!!

2024-09-28 13:33 UTC, jjt4515 commented on src/main/java/poomasi/domain/product/entity/Product.java
> +    private ProductStatus status = ProductStatus.PENDING;
상품 등록할 때 저희가 보고 승인을 한번 해줘야 한다면 필요할 것 같은데 일단은 없어도 될 것 같습니다

2024-09-28 13:35 UTC, jjt4515 commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +    public Long registerProduct(String token, ProductRegisterRequest product) {
토큰은 시큐리티에서 처리할 것입니다. 다만, 시큐리티에서 멤버 Role까지 확인하는지는 잘 모르겠네요
farmerId 받고 memberRole 확인하는 거 정도 넣어주면 되지 않을까요?

2024-10-01 05:26 UTC, stopmin commented on src/main/java/poomasi/domain/product/entity/Product.java
> +@SQLDelete(sql = "UPDATE farm SET deleted = true WHERE id = ?")
이거 Product로 바꿔주세용

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/category/controller/CategoryAdminController.java
> +@AllArgsConstructor
`@RequiredArgsConstructor`로 수정하셔야 할 것 같습니당~~ (제가 모르고 저걸 쓰고 있엇네요..ㅎㅎ)

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/category/controller/CategoryAdminController.java
> +    public ResponseEntity<?> modifyCategory(@PathVariable("category_id") Long categoryId,
pathVariable은 삭제하셔도 됩니다!!! 스네이크케이스로 따로 안하셔도 될 것 같아요~~

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/category/controller/CategoryAdminController.java
> +    @DeleteMapping("/api/categories/{category_id}")
snake case 안하셔도 될 것 같습니다~~

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/category/controller/CategoryController.java
> +@AllArgsConstructor
@RequiredArgsConstructor로 수정 부탁드려욤 (ㅈㅅㅈㅅ)

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/category/entity/Category.java
> +@NoArgsConstructor
@RequiredArgsConstructor로 수정 부탁드려욤 (ㅈㅅㅈㅅ)

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/category/service/CategoryAdminService.java
> +@AllArgsConstructor
@RequiredArgsConstructor... 부탁드려욤 ㅈㅅㅈㅅ

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/category/service/CategoryService.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/product/controller/ProductAdminController.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/product/controller/ProductAdminController.java
> +    ResponseEntity<?> openProduct(@PathVariable("product_id") Long productId) {
이부분도 카멜 케이스로 변경 부탁드려욤 ~~!!

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/product/dto/ProductRegisterRequest.java
> +                .quantity(0)
이 부분 지우셔야 할 것 같습니다~~~!! (깜박 하신듯!!)

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/product/entity/Product.java
> +@SQLSelect(sql = "SELECT * FROM farm WHERE status = ProductStatus.OPEN")
이부분은 JPA Repository로 따로 필터링 해서 가져오는 것이 좋겠다고 생각이 들어 수정해야할 것 같습니다~~! 왜냐하면, 이렇게 두면 OPEN이 아닌 곳들은 쿼리로 접근이 안되기 때문입니다 ㅠㅠ 유연성을 조금 더 높이고자...! 하핫 바쁘시면 제가 수정하겠습ㄴ디ㅏ!

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductAdminService.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2024-10-02 06:35 UTC, stopmin commented on src/main/java/poomasi/domain/product/service/ProductFarmerService.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2024-10-02 07:38 UTC, merged