Feature/issue 11
kakao-tech-campus-2nd-step3/Team10_BE pull request #20
Opened 2024-09-26 12:35 UTC by jjt4515

## 해결하려는 문제가 무엇인가요?

- close #11 

## 어떻게 해결했나요?

- jwtProvider 및 redis를 활용해 refreshToken 구현
- 일반 로그인, 회원가입, 로그아웃, 농부로 승격 구현

## 코드 리뷰시 요청 사항

- 카카오 로그인은 아직 못붙였습니다(시간상의 이슈)
- sns(카카오) 로 로그인한 계정과 로컬로 회원가입한 계정의 이메일이 중복될 경우 계정이 통합되도록 설계할 예정입니다. 피드백 환영
   - 카카오 로그인과 같은 이메일로 일반 회원가입 할 경우 계정 통합
   - 일반 회원가입 한 것과 같은 이메일로 카카오 로그인 할 경우 계정 통합
   - 통합시 로그인 타입은 LOCAL로 설정
- upgradeToFarmer에서 농부 인증이 됐는지 확인하기 위해 isValidBusinessRegistration를 임시로 작성하여 사업자 등록 번호가 있는지 확인하고 있습니다. 농부 인증 로직은 추후 논의해 봐야 할 거 같습니다

## 더 하고 싶은 말

- 화이팅~~

2024-09-27 03:53 UTC, stopmin requested changes
코드 잘 봤습니당😋 여러므로 많이 신경쓴 느낌이 많이 들었습니다!!! 보면서 나도 열심히해야지 동기부여가 팍팍됐습니다~~!!!
리뷰하면서 저도 많이 배워갔습니다!! 넘 잘짜신 것 같아요😀

리뷰사항 한번 확인 부탁드립니다~~~

### 추가적으로 질문사항
1. 왜 redis에 로그인 할 때 토큰을 저장하고, 로그아웃할 때 삭제하는지 궁금합니다.

보통 로그인 시에는 레디스에 토큰을 저장하는 것이 아니라, 클라이언트에 저장되고 요청이 있을 때마다 서버로 전달되는 구조라 딱히 로그인 후에는 토큰을 서버에서 가지고 있을 필요는 없다고 생각합니다.

다만 제가 알기로 @amm0124 님께서 redis를 활용하도록 한 동기는, "로그아웃 시 토큰을 저장하여" **누군가 이 토큰을 탈취하는 점을 우려하여 이를 저장해두기 위함**이라고 알고 있습니다. 즉, redis에 토큰이 다시 제출되면 블랙리스트로 관리되어있는 토큰에 포함되어 있을 경우 탈취된 토큰이라고 간주하고 무효화시키는 것입니다. (블랙 리스트 방식)

이와 관련되어서 건호님과 커뮤니케이션을 다시 한번 해보셔야 할 것 같습니다.

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/redis/service/RedisService.java
> +            return "false";
혹시 여기서 null이나 예외를 발생시키는 대신 "false"를 리턴하도록 한 동기가 궁금합니다~~!

예외를 던지거나 Optional<String>을 반환하는게 더 좋은 패턴이 아닌지 궁금합니다! 데이터가 없는 경우 null이 더 명확하지 않을까요?

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/redis/service/RedisService.java
> +    @Transactional(readOnly = true)
redis에 `@Transactional(readOnly=true)`가 필요한지 궁금합니다. redis는 일반적으로 트랜잭션이 필요없을 정도로 빠르고, 관리가 별도로 필요하지 않는 것으로 알고있습니다.

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/redis/service/RedisService.java
> +        values.set(key, data, duration);
Redis에 연결하는 것을 실패하거나 저장을 실패했을 때에 대한 예외 처리를 추가해야할 것 같습니다!

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/redis/service/RedisService.java
> +        redisTemplate.delete(key);
여기도 실패했을 때를 대비해 예외처리가 필요할 것 같습니다.

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/redis/service/RedisService.java
> +        Set<String> keys = redisTemplate.keys(pattern);
여기서 `keys()`대신 `SCAN`을 사용해보는건 어떨까 궁금합니다!

혹시 우려되어 검색해봤더니, `keys()`는 블로킹 연산이라, 모든 키를 가져오는 동안 해당 스레드를 차단한다고 합니다. 키가 아주아주... 많아진다면 부하가 발생할 수 있다고 합니다~~

[참고 글](https://medium.com/@shaskumar/redis-scan-vs-keys-command-9df7f51b7162)

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/util/JwtProvider.java
> +        secretKey = Keys.hmacShaKeyFor(secret.getBytes());
UTF-8을 명시해주는 것은 어떨까요~?

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/util/JwtProvider.java
> +    public String generateAccessToken(final String email, final Map<String, Object> claims) {
굿굿~~

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/util/JwtProvider.java
> +        }
JWT토큰에 대한 에러는 로그도 최대한 간결하고 중요한 정보는 제외시키면서 남기는게 좋지 않은지 궁금합니다.(진짜 궁금 궁금)

`e.getMessage()`까지 남겨도 되는가 궁금합니당

2024-09-27 03:53 UTC, stopmin commented on src/main/resources/application-secret.yml
> +  secret: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="
헉... secret이 깃에 올라왔네요 ㅠㅠ

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/entity/Role.java
> +public enum Role {
건호님이랑 일부 코드가 겹치는 것 같습니다! 추후에 두분 머지시킬 때 주의하셔야 할 것 같습니다.

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/error/BusinessError.java
> +	MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "회원이 존재하지 않습니다."),
앞에 // member 주석 부탁드립니다~~

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/error/BusinessError.java
> +	REFRESH_TOKEN_NOT_FOUND(HttpStatus.UNAUTHORIZED, "리프레시 토큰이 유효하지 않습니다."),
해당 에러는 Member에러라기보단 Auth에 관련된 에러네욤!

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/global/error/BusinessError.java
> +	INVALID_BUSINESS_REGISTRATION(HttpStatus.BAD_REQUEST, "유효하지 않은 사업자 등록번호입니다.");
이번 프로세스에서 사업자 등록 프로세스까지 다룬다면 과도한 스코프가 아닐지 싶습니다~~ 나중에 추가하셔도 괜찮을 것 같아요😀

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/entity/Member.java
> +@SQLDelete(sql = "UPDATE farm SET deleted = true WHERE id = ?")
farm -> member로 수정하셔야 할 것 같습니다~

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/entity/Member.java
> +@SQLSelect(sql = "SELECT * FROM farm WHERE deleted = false")
마찬가지로 farm -> member로 수정하셔야 할 것 같습니다~~

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/entity/MemberProfile.java
> +    private boolean isSuspended;
혹시 정지계정을 목적으로 두신 것 같은데, `isSuspend()`라는 메소드가 이미 JPA에 있지 않나 궁금합니다.

정지 계정을 고려해서 기획했었는지는 잘 모르겠으나 네이밍은 조금 개선이 필요할 것 같습니다!

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/controller/AuthController.java
> +public class AuthController {
Auth에 관련된 부분은 Member가 아닌 인가인증 도메인에 있어도 괜찮을 것 같습니다.

회원 정보 생성 보다는 인증 프로세스/인증 토큰에 관련된 프로세스같은데, Auth로 이동시키는 것은 어떤가 궁금합니다!

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +    // 사업자 등록 번호 검사 로직은 추후 논의 필요
사업자 등록 번호에 대한 로직은 어느정도 MemberService와의 분리가 필요할 것 같네요! 다른 파일에서 작업하셔도 될 것 같습니다.

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +    }
`Lombok`을 사용하기 때문에 `@RequiredArgsConstructor`로 의존성 주입 하시면 될 것 같습니다~

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new BusinessException(MEMBER_NOT_FOUND));
해당 코드는 어느정도 계속 비지니스 로직상 반복될 코드라고 생각합니다!
항상 가져올 때마다 멤버가 있는지 없는지 검증하는 것은 copy and paste반복이니, member Service내부에서 하나의 메소드로 생성하여 사용하는게 좋지 않을까 싶습니다!!

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +public class MemberService {
여기서는 개인적으로 인증/인가 (JWT 등..) 대신에 사용자 정보에 대한 로직이 있어야하지 않을까 싶습니다! 로그인과 로그아웃은 조금 거리가 먼 부분인 것 같습니다.

2024-09-27 03:53 UTC, stopmin commented on src/main/java/poomasi/domain/member/controller/AuthController.java
> +    @PostMapping("/signUp")
endpoint는 주로 카멜케이스 보다는 하이푼이나 소문자를 사용을 지향합니다 :)

2024-09-27 13:30 UTC, jjt4515 commented on src/main/java/poomasi/global/util/JwtProvider.java
> +        }
e.getMessage()는 없애는 게 맞는거 같아요

2024-09-27 13:34 UTC, jjt4515 commented on src/main/java/poomasi/global/util/JwtProvider.java
> +        }
최대한 간결하게 변경했습니다

2024-09-27 13:38 UTC, jjt4515 commented on src/main/resources/application-secret.yml
> +  secret: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="
헉...

2024-09-27 13:48 UTC, jjt4515 commented on src/main/java/poomasi/domain/member/entity/Member.java
> +@SQLDelete(sql = "UPDATE farm SET deleted = true WHERE id = ?")
어.. 맞네요

2024-09-27 13:51 UTC, jjt4515 commented on src/main/java/poomasi/domain/member/controller/AuthController.java
> +public class AuthController {
조금만 더 생각해보겠습니다..!

2024-09-27 13:51 UTC, jjt4515 commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +    // 사업자 등록 번호 검사 로직은 추후 논의 필요
boolean을 입력받도록 변경했습니다

2024-09-27 13:56 UTC, jjt4515 commented on src/main/java/poomasi/domain/member/entity/MemberProfile.java
> +    private boolean isSuspended;
isBanned()로 변경했습니다

2024-09-27 14:07 UTC, jjt4515 commented
레디스 관련 부분은 이후에 수정하겠습니다.
회원가입, 로그아웃 로직을 auth 폴더로 옮겼는데, upgradeToFarmer는 member or auth 어디에 둘지 헷갈리네요

2024-09-28 05:16 UTC, stopmin commented on src/main/java/poomasi/domain/member/entity/Member.java
> +@SQLDelete(sql = "UPDATE farm SET deleted = true WHERE id = ?")
굿굿~~

2024-09-28 05:16 UTC, stopmin commented on src/main/java/poomasi/domain/member/entity/MemberProfile.java
> +    private boolean isSuspended;
좋습니다~

2024-09-28 05:21 UTC, stopmin approved these changes
![sheep](https://github.com/user-attachments/assets/bf0552d3-3bf0-4f04-be97-d1d2654f0ab3)
Redis부분은 따로 이슈 만드셔서 나중에 작업하셔도 괜찮을 것 같아요 :D
LoginReequest도 auth쪽으로 이동시키고 머지 하시면 될거같아요!!

수고하셨어요 😃😃

2024-09-28 11:26 UTC, merged

2024-09-29 05:17 UTC, jjt4515 commented
upgradeToFarmer는 member 폴더로 가는게 맞는거 같아요 토큰은 안다루고 memberRole만 변경시키기 때문에

2024-09-30 00:43 UTC, amm0124 commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +import poomasi.global.util.JwtProvider;
인증/인가 로직에서 Provider는 인증을 수행하는 객체입니다
JwtUtil이라는 이름이 더 어울릴 것 같아요

2024-09-30 00:44 UTC, amm0124 commented on src/main/java/poomasi/global/util/JwtProvider.java
> +    public String getSubjectFromToken(final String token) {
subject만 추출하는 것이 아닌 email 자체를 추출하는 메서드가 있으면 좋겠습니다 ~

2024-09-30 05:16 UTC, jjt4515 commented on src/main/java/poomasi/global/redis/service/RedisService.java
> +    @Transactional(readOnly = true)
오 Redis는 비관계형 데이터를 처리하기 때문에 @Transactional(readOnly=true)가 필요없다고 하네요

2024-09-30 05:23 UTC, jjt4515 commented on src/main/java/poomasi/global/util/JwtProvider.java
> +        }
로그는 외부에서 못 봐서 상관없다고 하는데, 실제로 그런지 잘 모르겠네요..

2024-09-30 05:49 UTC, jjt4515 commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +import poomasi.global.util.JwtProvider;
제가 알기로는 jwtProvider는 jwt 제공 및 검증을 담당하는 객체여서 문제되진 않을 것 같아요
수정하는게 어렵지 않아서 바꾸도록 하겠습니다

2024-09-30 06:12 UTC, jjt4515 commented on src/main/java/poomasi/global/util/JwtProvider.java
> +    public String getSubjectFromToken(final String token) {
subject = email이라 email을 추출하긴 합니다.
그런데 subject가 바껴도 무조건 email만 추출할 수 있도록 코드를 수정하였습니다.

2024-09-30 06:21 UTC, jjt4515 commented on src/main/java/poomasi/global/redis/service/RedisService.java
> +            return "false";
맞습니다

2024-09-30 06:39 UTC, amm0124 commented on src/main/java/poomasi/global/util/JwtProvider.java
> +    public String getSubjectFromToken(final String token) {
아 아까 컴퓨터가 꺼져서 댓글을 다 못달았네요
token을 발급하는 과정을 간단하게 설명해드릴게용. 아시겠지만!!! 머릿속에서 잊으면 안 되는 것이 token은 인증이 완료된 사람에 한해서 발급을 해야 합니다!! 

앞부분은 생략하겠습니다. 현재 필터는 UsernamePasswordAuthenticationFilter입니다. 이 필터는 로그인 및 토큰을 발급하는 토큰입니다!.

security filter chain - UsernamePasswordAuthenticationFilter의 AuthenticationManager을 상속받은 ProviderManager의 구현체 AuthenticaitonProvider(지난 주 금요일 대면 회의에서 말했던! - passwordEncoder, UserDetailService를 필요로 하는 실제 인증을 하는 객체)가,

user detail service(db에 접근하며 Member 정보를 가져오는 service라고 이해하시면 될 것 같아요)를 사용하여, db에 있는 즉, 회원가입이 완료된 Member 객체를 가져옵니다. 

이 객체(Member)는 Role을 가지고 있는 객체입니다(이미 회원 가입이 완료된 객체니까요). 이후 token claim에 email과 role을 넣어서 token을 발급해야 해요. 따라서 subject에는 email만 들어 있는 것이 아닌, role도 포함이 되어야 합니다. 그렇지 않으면 매번 컨트롤러에서 security context (인증할 때 정보를 유지하는 메모리 정도라고 생각하시면 될 것 같아요. context에는 인증이 완료되지 않은 객체는 false, 인증이 완료된 객체는 true로 저장됩니다.) 의 email을 조회한 다음, Role을 찾아야 하기 때문이에요. claim에 role을 넣으면 @PreAuthorization 혹은 @Secured annotation으로 간략하게 컨트롤러 선에서 인가를 할 수 있기 때문입니다. 

이후, UsernamepasswordAuthenticationFilter의 successfulAuthentication 메서드를 Overriding하여 token을 발급해야 해요!  이러한 이유로 subject에는 email만 들어가는 것이 아닌, User Role도 들어가야 합니다 ~.~

결론 
- token 만들 때, email 뿐 아니라, user role도 들어가야 해요.
- subject 추출 후, email과 role도 추출하는 메서드가 필요합니다!

2024-09-30 06:41 UTC, amm0124 commented on src/main/java/poomasi/domain/member/service/MemberService.java
> +import poomasi.global.util.JwtProvider;
검증을 담당하는 객체려면 authentication 메서드를 overriding 해야 합니다. 즉 security context에 직접적으로 접근을 하는 객체여야 해요. 하지만 jwt Provider는 context에 직접 접근을 하지 않아서 jwt util이라는 이름이 적당해보인다고 생각했습니다 ~. 이름은 취향껏이긴 하지만요

2024-10-01 05:17 UTC, jjt4515 commented on src/main/java/poomasi/global/util/JwtProvider.java
> +    public String getSubjectFromToken(final String token) {
넵 반영하겠습니다