feat: product tag 생성
kakao-tech-campus-2nd-step3/Team10_BE pull request #72
Opened 2024-10-22 09:22 UTC by canyos

## 해결하려는 문제가 무엇인가요?

- close #37

## 어떻게 해결했나요?

- 간단하게 만들어봣습니다

## 코드 리뷰시 요청 사항

- enum select가 안되길래 native로 짰는데 jpql로 하는 방법 아시면 알려주세욥

## 더 하고 싶은 말

-

2024-10-28 06:28 UTC, stopmin requested changes
혹시 product tag는 그냥 product에 tag를 enum으로 두도록 하는건 어떤지 싶습니다!!! 이것까지 Entity로 관리하면 조금 오버 엔지니어링 같은 느낌이 드네요😢

2024-10-29 09:16 UTC, canyos commented
@stopmin enum으로 관리하게 바꿔봤습니다

2024-10-30 12:13 UTC, stopmin commented on src/main/java/poomasi/domain/product/entity/Product.java
> +    @ElementCollection(fetch = FetchType.EAGER)
혹시 Lazy대신 Eager로 설정하신 이유가 궁금합니다!!!

2024-10-30 12:13 UTC, stopmin commented on src/main/java/poomasi/domain/review/dto/ReviewResponse.java
> +         Long entityId,
product, farm 둘다 쓸 ㅇ예정이라 Entity로 네이밍을 수정하신건지 궁금합니다!

2024-10-31 06:38 UTC, jjt4515 commented on src/main/java/poomasi/domain/product/entity/ProductTagEnum.java
> +    NonPesticide("무농약");
enum이니깐
NON_PESTICIDE("무농약"); 으로 쓰는 것은 어떨까요?

2024-10-31 06:38 UTC, jjt4515 commented on src/main/java/poomasi/domain/product/service/ProductTagService.java
> +        return productRepository.findById(productTagRequest.productId())
findByIdAndDeletedAtIsNull로 바꾸는 것은 어떨까요? 
혹시 제가 틀린 거라면 바로 피드백 주시면 감사하겠습니당

2024-10-31 06:38 UTC, jjt4515 commented on src/main/java/poomasi/domain/product/service/ProductTagService.java
> +        try {
이 부분은 addTag에 있는 로직과 동일해서 공통화시키면 좋을 것 같다는 생각이 듭니당

2024-10-31 06:38 UTC, jjt4515 commented on src/main/java/poomasi/domain/review/dto/ReviewResponse.java
> +         Long entityId,
저는 product랑 farm이랑 id값이 중복될 수 있으니 따로 type을 받아야겠다 생각했는데
ReviewRepository에서    
@Query("select r from Review  r where r.entityId = :productId and r.entityType = 'PRODUCT'")
와 같은 쿼리문 써서 type 받을 필요도 없도록 잘 구현해주셨네요 하나 배웠습니다~!

2024-11-02 11:03 UTC, amm0124 commented
고생하셨습니다!

2024-11-02 17:43 UTC, canyos commented on src/main/java/poomasi/domain/review/dto/ReviewResponse.java
> +         Long entityId,
네네 둘다쓸거라 entity로했습니다.

2024-11-02 17:43 UTC, canyos commented on src/main/java/poomasi/domain/product/entity/Product.java
> +    @ElementCollection(fetch = FetchType.EAGER)
단일상품을 조회하면 필요하다고 생각했는데 상품리스트 조회할때도 같이 나오겠네요 lazy로 변경하겠스빈다

2024-11-02 17:43 UTC, canyos commented on src/main/java/poomasi/domain/product/entity/ProductTagEnum.java
> +    NonPesticide("무농약");
넵

2024-11-02 17:44 UTC, canyos commented on src/main/java/poomasi/domain/product/service/ProductTagService.java
> +        return productRepository.findById(productTagRequest.productId())
이거는 소프트 삭제를 안하기로했던걸로 해두겠스빈다 일단

2024-11-02 17:44 UTC, canyos commented on src/main/java/poomasi/domain/product/service/ProductTagService.java
> +        try {
확인해보겟습니다

2024-11-05 08:52 UTC, merged